# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://jonhuffaker.com
title: Jon Huffaker
email: jonathanhuffaker@gmail.com
author: Jon Huffaker
description: > # "Write an awesome description for your new site here. 
  Full stack software developer with skills in CSS, Javascript, Angular, JQuery, and C#
copyright: 'Copyright &copy; 2016 Jon Huffaker. All Rights Reserved.'
credits: 'Credits: Landing Page by Start Bootstrap'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/j_huffaker
  - title: github
    url: https://github.com/jonathanhuffaker
  - title: linkedin
    url: https://www.linkedin.com/in/jonathan-huffaker-94321368
